services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\EventSubscriber\PaginateRawResultSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    DynamicSearchBundle\EventSubscriber\DataProcessingEventSubscriber: ~

    DynamicSearchBundle\EventSubscriber\ErrorEventSubscriber: ~

    DynamicSearchBundle\EventDispatcher\DynamicSearchEventDispatcherInterface: '@DynamicSearchBundle\EventDispatcher\DynamicSearchEventDispatcher'
    DynamicSearchBundle\EventDispatcher\DynamicSearchEventDispatcher: ~

    DynamicSearchBundle\EventListener\PimcoreElementListener:
        tags:
            - { name: kernel.event_subscriber }

    DynamicSearchBundle\EventListener\ProviderAvailabilityListener:
        tags:
            - { name: kernel.event_subscriber }
